language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
    allow_failures:
        - php: 7.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
